### ISSUE TITLE
Classification data in 'treeherder' table has stopped updating

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/ActiveData#159]
Classification data in 'treeherder' table has stopped updating, [fresh](https://charts.mozilla.org/FreshOranges/index.html) and [neglected](https://charts.mozilla.org/NeglectedOranges/index.html) oranges are empty.

The [query](https://activedata.allizom.org/tools/query.html#query_id=10D08Xnp) from neglected oranges gets maximum 11 classifications for a bug during the last week but  it has been [classified more often](https://treeherder.mozilla.org/intermittent-failures.html#/bugdetails?startday=2019-08-10&endday=2019-08-17&tree=all&bug=1358898).

The [newest bug used for classification](https://activedata.allizom.org/tools/query.html#query_id=Pgi2PVgM) is a week old.

**Comment by jmaher** [comment]
@klahnakoski can you help get this online when you get back on Monday?

**Comment by klahnakoski** [comment]
The ES ingestion had started to fall behind Wed Aug 7, I noticed on Fri Aug 9th; and reboot the ETL machines, and hoped it would catch up over the weekend.  Mon Aug 12 showed no progress, so a fix was found (https://github.com/klahnakoski/ActiveData-ETL/issues/58), over the week ES ingestion proved to be slow, but I was optimistic.  Fri Aug 16th the ingestion was still far behind (https://mozilla.logbot.info/activedata/20190816) so I turned down coverage ingestion so the rest of the data could catch up.

Over the weekend, ingestion improved and it is now working on Aug15.  Hopefully it will be almost done by the end of today.  More on #activedata

**Comment by klahnakoski** [comment]
@Archaeopteryx please confirm that the problem has gone away, and close this issue if so.  Thank you

**Comment by klahnakoski** [comment]
@klahnakoski for my own notes: I think this is the cause:  https://github.com/mozilla/ActiveData/issues/160

**Comment by Archaeopteryx** [comment]
Thanks, looks okay to me.
