### ISSUE TITLE
Support 'table' format for large result sets queries

### ISSUE THREAD

**Issue by marco-c** [mozilla/ActiveData#186]

**Comment by klahnakoski** [comment]
done

**Comment by marco-c** [comment]
@klahnakoski the result from a large result set query with `format: table` is a bit different than normal `format: table` queries:
1) normal queries have a `header` field with the column names and a `data` field with the columns; large result set queries have those fields under another `data` field;
2) in normal queries results, the `format` field is `table`; in large result set queries results, the `format` field is `list`;
3) normal query results have a few additional keys that large result set query results don't have.

Is it on purpose? Note I only really care about 1 for mozci usage.

**Comment by klahnakoski** [comment]
It turns out there was no extra `data` property, but there was wrong and missing `meta.format` properties, which are now tested for, and fixed
