### ISSUE TITLE
json formatter link 

### ISSUE THREAD

**Issue by maggienj** [mozilla/ActiveData#45]
i guess the subdomain people.mozilla.org doesn't exist. So, json formatter link isn't working in this page, https://github.com/klahnakoski/ActiveData/blob/master/docs/GettingStarted.md

**Comment by klahnakoski** [comment]
Thank you! I also noticed it was gone, but I forgot I linked to it.

**Comment by klahnakoski** [comment]
A very basic JSON formatter

https://charts.mozilla.org/JSON-Formatter/index.html
