### ISSUE TITLE
Expose ActiveData through https+password with elasticsearch-readonlyrest-plugin

### ISSUE THREAD

**Issue by La0** [mozilla/ActiveData#69]
This Elasticsearch java plugin [elasticsearch-readonlyrest-plugin](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin) could replace esFrontline, and offer several advantages:

* actively tested & maintained
* removes the gunicorn perf bottleneck
* directly integrated into ES frontend server
* Allows SSL without nginx as frontend
* Support users/groups/indexes limitation (we could have a `codecoverage` user allowing RO access to `coverage` & `repo` only)

@klahnakoski What do you think ? I can test this solution on a local cluster & report back with a documentation & integration in your deployment

**Comment by klahnakoski** [comment]
This sounds like a good find!

**Comment by marco-c** [comment]
This might help with the timeout issues we are seeing.

**Comment by La0** [comment]
@klahnakoski I [successfully tested](https://gist.github.com/La0/54d5a9b368b860516d37bbb861d75590) the plugin on a docker instance of Elasticsearch 6.1.2, with  a user/password hashed (sha256)

I'm making a PR to update `resources/scripts/setup_frontend_r3_large.sh` on the **dev** branch. Would that work for you ?

**Comment by klahnakoski** [comment]
The [frontend6](https://github.com/mozilla/ActiveData/tree/frontend6) branch is the best place to land code destined for the frontend of the new cluster. `dev` branch will eventually be merged into `frontend6` branch  (and visa-versa), but it will be a while as `dev` branch is usually in a bad state.

**Comment by klahnakoski** [comment]
@La0 If you are good with this, please close it.
