### ISSUE TITLE
neq should be supported

### ISSUE THREAD

**Issue by Callek** [mozilla/ActiveData#70]
So, from moz-sql-parser (not sure if this is a bug in that or here)

```
>>> parse("""
... select build.product from tasks where foo != "firefox"
... """)
{'select': {'value': 'build.product'}, 'from': 'tasks', 'where': {'neq': ['foo', 'firefox']}}
```
While activedata supports "ne".. https://github.com/mozilla/ActiveData/blob/dev/docs/jx_expressions.md#ne-operator
Specifically in this case I'd have expected it to be `... 'where': {'ne': {'foo', 'firefox'}}}`

@klahnakoski thoughts?

**Comment by klahnakoski** [comment]
ActiveData has some aliases for operators; both `ne` and `neq` are valid and the same:  https://github.com/mozilla/ActiveData/blob/master/pyLibrary/queries/expressions.py#L3038

Your original SQL is wrong:

```sql
select build.product from tasks where foo != "firefox"
```

Unlike Python, SQL double quotes are different than single quotes.  The double quotes are for declaring variable and table names, while single quotes are for quoting literal strings.  The `"firefox"` is referring to the "firefox" variable, which does not exist. 

Plus, the`tasks`table does not exist; it can;t be plural; use `task` 

```sql
select build.product from task where foo != 'firefox'
```
