### ISSUE TITLE
changeset.description is returning null

### ISSUE THREAD

**Issue by ahal** [mozilla/ActiveData#74]
This is cloned from: https://github.com/mozilla/active-data-recipes/issues/32

The try_usage recipe does not work using the new cluster. The data it needs is there, but {"select":"changeset.description"} is returning null.

{
	"from":"repo",
	"select":["push.user","changeset"],
	"where":{"and":[
		{"eq":{"branch.name":"try"}},
		{"gte":{"push.date":{"date":"today-week"}}}
	]},
	"sort":{"push.user":"desc"},
	"limit":10
}

The repo is not storing the description separate from the whole document.

**Comment by klahnakoski** [comment]
fixed in dev

see https://github.com/mozilla/ActiveData/issues/80

**Comment by klahnakoski** [comment]
This is working now

https://activedata.allizom.org/tools/query.html#query_id=iEFg0x+T
