### ISSUE TITLE
redash sql not working

### ISSUE THREAD

**Issue by klahnakoski** [mozilla/ActiveData#96]
This query does not work.  The biggest problem being the (?parse?) error is not getting back to redash user

```
select 
    count("result.stats.s1") 
from 
    perf 
where 
    "run.timestamp">=date('today-month') and 
    "run.framework.name" = 'vcs' and 
    "run.suite"='clone' 
group by 
    floor("run.timestamp", 86400) as "day"
```

**Comment by klahnakoski** [comment]
Testing of the sql parser shows it is fine, making me think there is an issue with the communication chain

**Comment by klahnakoski** [comment]
The error arrives via email:

```
ERROR: Shard failures 	[
	    {
	        "caused_by": {
	            "reason": "class_cast_exception: Cannot apply [/] operation to types [org.elasticsearch.index.fielddata.ScriptDocValues.Doubles] and [java.lang.Integer].",
	            "type": "class_cast_exception"
	        },
	        "lang": "painless",
	        "reason": "runtime error",
	        "script": "Math.floor((doc[\"run.timestamp.~n~\"].values) / (86400))*(86400)",
	        "script_stack": [
	            "Math.floor((doc[\"run.timestamp.~n~\"].values) / (86400))*(86400)",
	            "                                    ^---- HERE"
	        ],
	        "type": "script_exception"
	    }
	]
```

**Comment by klahnakoski** [comment]
Painless does not have this problems

**Comment by cgsheeh** [comment]
Hey @klahnakoski , could you elaborate on what you mean? Is querying from redash working now?

**Comment by klahnakoski** [comment]
@cgsheeh That particular query was failing because of the version of Elasticsearch, and its scripting language, which could not handle float/integer.  The current version in use is a bit more forgiving, and the query now works.

querying from redash has always been "working" (passes all tests).
